name: pyapireference
title: PyAPIReference
contact: cristobalriaga@gmail.com
issues: https://github.com/Patitotective/PyAPIReference/issues
source-code: https://github.com/Patitotective/PyAPIReference
website: https://patitotective.github.io/PyAPIReference/
license: MIT
version: '0.1.50'
summary: Python modules API Reference generator
description: |
  PyAPIReferences is a GUI application made with PyQT5 to generate API References for Python modules. 
  Once after downloading the PyAPIReferences, open it and load the Python module where you want to obtain the API Reference. 
  It will create a tree with the Python module members (classes, functions, etc), in that tree you can check and uncheck the members you want to include in the API Reference. 
  Switch to API Reference tab and click Generate API Reference, it will geneate a Markdown text that you can edit and live preview. 
  When you finish editing it you can export it as HTML, Markdown or ReStructured Text.
base: core20
confinement: devmode
parts:
  pyapireference:
    plugin: python
    source: .
apps:
  pyapireference:
    command: bin/PyAPIReference
